services:
  azure-proxy:
    container_name: azure-proxy
    build:
      context: .
      dockerfile: deploy/docker/Dockerfile
    image: azure-proxy:latest
    restart: unless-stopped
    environment:
      - SERVER_BIND=0.0.0.0:8000
      - LOG_LEVEL=info
    ports:
      - 8000:8000
    volumes:
      - ./config:/etc/azure-proxy
      - ./logs:/var/log/azure-proxy
